# Generated by Django 5.2.11 on 2026-02-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_api', '0002_productcategory_storagelocation_supplier_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '系统管理员'), ('supervisor', '仓库管理员'), ('operator', '普通查询员')], default='operator', max_length=20, verbose_name='系统角色'),
        ),
    ]
